version: "2.3"
services:

  db:
    extends:
        file: mariadb/db-runtime.yml
        service: db

  web:
    extends:
        file: tomcat/web-runtime.yml
        service: web
    links:
        - db   

